pull_request_rules:
  - name: merge [bot] PRs when CI pass
    conditions:
      - check-success = "check-macos-linux-nix"
      - check-success = "pre-commit.ci - pr"
      - or:
          - author = dependabot[bot]
          - author = gepetto-flake-updater[bot]
          - author = mc-rtc-nixpkgs-flake-updater[bot]
          - author = github-actions[bot]
          - author = pre-commit-ci[bot]
    actions:
      merge:
  - name: merge on maintainer comment and CI pass
    conditions:
      - check-success = "check-macos-linux-nix"
      - check-success = "pre-commit.ci - pr"
      - comment-body~="@mergify merge"
      - author~=^(arntanguy|ThomasDuvinage)$  # Replace with actual GitHub usernames
    actions:
      merge:
