pull_request_rules:
  - name: queue [bot] PRs when CI pass
    conditions:
        - author = dependabot[bot]
        - author = gepetto-flake-updater[bot]
        - author = mc-rtc-nixpkgs-flake-updater[bot]
        - author = github-actions[bot]
        - author = pre-commit-ci[bot]
    actions:
      queue:

  - name: queue PRs with merge-queue label when all CI checks pass
    conditions:
      - label = queued
    actions:
      queue:

queue_rules:
  - name: default
    conditions:
      - check-success = "check-macos-linux-nix"
      - check-success = "check-wait"
      # - check-success = "pre-commit.ci - pr"
